import { National } from "./national";


export const lesNations: National [] = [
    {
      id: 1,
      capital: "Paris",
      region: "Europe",
      name: "France",
      altSpellings: ["République française", "French Republic"],
      area: 643801,
    },
    {
      id: 2,
      capital: "Berlin",
      region: "Europe",
      name: "Germany",
      altSpellings: ["Deutschland"],
      area: 357168,
    },
    {
      id: 3,
      capital: "London",
      region: "Europe",
      name: "United Kingdom",
      altSpellings: ["UK", "Britain"],
      area: 242495,
    },
    {
      id: 4,
      capital: "Washington, D.C.",
      region: "Americas",
      name: "United States",
      altSpellings: ["USA", "America"],
      area: 9833520,
    },
    {
      id: 5,
      capital: "Tokyo",
      region: "Asia",
      name: "Japan",
      altSpellings: ["Nihon", "Nippon"],
      area: 377975,
    },
    {
      id: 6,
      capital: "Beijing",
      region: "Asia",
      name: "China",
      altSpellings: ["Zhōngguó", "People's Republic of China"],
      area: 9596961,
    },
    {
      id: 7,
      capital: "New Delhi",
      region: "Asia",
      name: "India",
      altSpellings: ["Bhārat", "Republic of India"],
      area: 3287263,
    },
    {
      id: 8,
      capital: "Moscow",
      region: "Europe/Asia",
      name: "Russia",
      altSpellings: ["Rossiya", "Russian Federation"],
      area: 17124442,
    },
    {
      id: 9,
      capital: "Brasília",
      region: "Americas",
      name: "Brazil",
      altSpellings: ["Brasil", "Federative Republic of Brazil"],
      area: 8515767,
    },
    {
      id: 10,
      capital: "Cairo",
      region: "Africa",
      name: "Egypt",
      altSpellings: ["Mişr", "Arab Republic of Egypt"],
      area: 1002450,
    },
  ];